version: "3.5"
services:
  schools:
    image: mysql:debian
    container_name: "masterdb"
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=school_inventory
    volumes:
      - school_inventory:/var/lib/mysql
      - ./tables/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./triggers/triggers.sql:/docker-entrypoint-initdb.d/triggers.sql
      - ./triggers/shadowTriggers.sql:/docker-entrypoint-initdb.d/shadowTriggers.sql
      - ./store-procedures/store-procedures.sql:/docker-entrypoint-initdb.d/store-procedures.sql
      - ./data/data.sql:/docker-entrypoint-initdb.d/data.sql
    volumes:
      school_inventory:
