version: "3.5"
services:
  schools:
    image: mysql:debian
    container_name: "masterdb"
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=school_inventory
    volumes:
      - school_inventory:/var/lib/mysql
      - ./tables/01_init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./triggers/03_triggers.sql:/docker-entrypoint-initdb.d/triggers.sql
      - ./triggers/02_shadowTriggers.sql:/docker-entrypoint-initdb.d/shadowTriggers.sql
      - ./store-procedures/04_store-procedures.sql:/docker-entrypoint-initdb.d/store-procedures.sql
      - ./data/05_data.sql:/docker-entrypoint-initdb.d/data.sql
volumes:
  school_inventory:
