version: "3.5"
services:
  schools:
    image: mysql:debian
    container_name: "masterdb"
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=school_inventory
    volumes:
      - school_inventory:/var/lib/mysql
      - ./tables/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./triggers/03_triggers.sql:/docker-entrypoint-initdb.d/03_triggers.sql
      - ./triggers/02_shadowTriggers.sql:/docker-entrypoint-initdb.d/02_shadowTriggers.sql
      - ./store-procedures/04_store_procedures.sql:/docker-entrypoint-initdb.d/04_store_procedures.sql
      - ./data/05_data.sql:/docker-entrypoint-initdb.d/05_data.sql
volumes:
  school_inventory:
