version: "3.5"
services:
  schools:
    image: mysql:debian
    container_name: "masterdb"
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=school_inventory
    volumes:
      - ./tables/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./indexes/indexes.sql:/docker-entrypoint-initdb.d/indexes.sql
      - ./triggers/triggers.sql:/docker-entrypoint-initdb.d/triggers.sql
      - ./store-procedures/store-procedures.sql:/docker-entrypoint-initdb.d/store-procedures.sql
      - ./data/data.sql:/docker-entrypoint-initdb.d/data.sql
      - mysqldata_master:/var/lib/mysql
